
submit_ticket:
    path:     /tickets/submit
    defaults: { _controller: AppBundle:Sales:submitTicket }

ticket_submission_successful:
    path:     /tickets/submit/success
    defaults: { _controller: AppBundle:Sales:ticketSubmissionSuccessful }

login_submission:
    path:     /login/submit
    defaults: { _controller: AppBundle:Login:submitLogin }
